version: 2
updates:
  # Python dependencies from requirements.txt
  - package-ecosystem: "pip"
    directory: "/" # Root directory
    schedule:
      interval: "daily"

  # Ruby dependencies from Gemfile (e.g. github-pages)
  - package-ecosystem: "bundler"
    directory: "/" # Root directory
    schedule:
      interval: "daily"

  # GitHub Actions used in main.yml
  - package-ecosystem: "github-actions"
    directory: ".github/workflows"
    schedule:
      interval: "daily"
