name: Build KataGo for ARM (Ubuntu)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-katago:
    runs-on: ubuntu-latest
    env:
      BUILD_THREADS: 4
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Compatible with runner v2.323.0
    
    - name: Set up ARM build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git cmake build-essential \
          gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf \
          libzip-dev libboost-dev libboost-filesystem-dev \
          libboost-system-dev libopenblas-dev libeigen3-dev
        
    - name: Clone KataGo source
      run: |
        git clone --recursive https://github.com/lightvector/KataGo.git
        mkdir -p KataGo/toolchains
        curl -o KataGo/toolchains/arm-linux-gnueabihf.cmake \
          https://raw.githubusercontent.com/lightvector/KataGo/master/toolchains/arm-linux-gnueabihf.cmake
        
    - name: Configure for ARM
      run: |
        cd KataGo/cpp
        cmake . \
          -DUSE_BACKEND=EIGEN \
          -DNO_GIT_REVISION=1 \
          -DCMAKE_TOOLCHAIN_FILE=../../toolchains/arm-linux-gnueabihf.cmake \
          -DCMAKE_C_COMPILER=arm-linux-gnueabihf-gcc \
          -DCMAKE_CXX_COMPILER=arm-linux-gnueabihf-g++ \
          -DCMAKE_BUILD_TYPE=Release
        
    - name: Build KataGo
      run: |
        cd KataGo/cpp
        make -j$BUILD_THREADS
        arm-linux-gnueabihf-strip katago
        
    - name: Verify binary
      id: verify
      run: |
        if [ -f KataGo/cpp/katago ]; then
          echo "::set-output name=status::success"
          echo "Binary verification passed"
          file KataGo/cpp/katago
        else
          echo "::set-output name=status::failure"
          exit 1
        fi
        
    # Manual artifact packaging for older runners
    - name: Package artifact
      if: steps.verify.outputs.status == 'success'
      run: |
        mkdir -p artifact
        cp KataGo/cpp/katago artifact/
        tar czvf katago-arm.tar.gz -C artifact .
        
    - name: Upload artifact (manual method)
      if: steps.verify.outputs.status == 'success'
      run: |
        echo "::warning::Using manual artifact upload due to runner limitations"
        curl -X POST \
          -H "Authorization: Bearer ${{ github.token }}" \
          -H "Content-Type: application/json" \
          "https://api.github.com/repos/${{ github.repository }}/actions/artifacts" \
          -d '{"name":"katago-arm","size":$(stat -c%s katago-arm.tar.gz),"archive_format":"zip"}'
        
    - name: Success status
      if: steps.verify.outputs.status == 'success'
      run: |
        echo "::notice title=Build Success::ARM binary compiled successfully"
        echo "KataGo Version: $(./KataGo/cpp/katago version)"
        
    - name: Failure handler
      if: steps.verify.outputs.status == 'failure'
      run: |
        echo "::error title=Build Failed::ARM compilation failed"
        exit 1
